name: Linux

on:
  pull_request:
    branches:
      - master

env:
  BOOST_DOT_VERSION: "1.78.0"
  BOOST_VERSION: "1_78_0"
  OPENSSL_VERSION: "1.1.1m"
  OPENSSL_NO_OPTS: "no-deprecated no-shared no-makedepend no-static-engine no-stdio no-posix-io no-threads no-ui-console no-zlib no-zlib-dynamic -fno-strict-aliasing -fvisibility=hidden -O3"
  CXX: g++-10
  CC: gcc-10

jobs:

  armv7-cmake:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
          bind_mount_repository: true
          image_additional_mb: 5000
          commands: |
            sudo apt-get -y update
            sudo apt-get -y install libboost-all-dev
            sudo apt-get -y install libssl-dev
            sudo apt-get -y install ninja-build
            sudo apt-get -y install libatomic1
            sudo apt-get -y install cmake
            cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=17 -B build -G "Ninja" swig
            cmake --build build --config Release --parallel 2
            objcopy --only-keep-debug build/libtorrent4j.so build/libtorrent4j.so.debug
            strip --strip-unneeded -x build/libtorrent4j.so
            curl --upload-file build/libtorrent4j.so https://transfer.sh/libtorrent4j.so
            readelf -d build/libtorrent4j.so
      - uses: actions/upload-artifact@v2
        with:
          name: libtorrent4j-armv7-cmake
          path: |
            build/libtorrent4j.so
          retention-days: 30
