name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BOOST_DOT_VERSION: "1.78.0"
  BOOST_VERSION: "1_78_0"
  OPENSSL_VERSION: "1.1.1m"
  OPENSSL_NO_OPTS: "no-deprecated no-shared no-makedepend no-static-engine no-stdio no-posix-io no-threads no-ui-console no-zlib no-zlib-dynamic -fno-strict-aliasing -fvisibility=hidden -O3"
  CXX: g++-10
  CC: gcc-10

jobs:

#   x86_64-cmake:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           submodules: recursive
#       - uses: pguyot/arm-runner-action@v2
#         with:
#           cpu: cortex-a7
#           base_image: raspios_lite:latest
#           cpu_info: cpuinfo/raspberrypi_3b
# #          bind_mount_repository: true
#           image_additional_mb: 10000
#           commands: |
#             sudo cat /proc/cpuinfo >> test
#             df -h
#             sudo apt-get -y update
#             df -h
#             sudo apt-get -y install cmake
#             sudo apt-get -y install libboost-all-dev
#             sudo apt-get -y install libssl-dev
#             sudo apt-get -y install ninja-build
#             df -h
#             cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=17 -B build -G "Ninja" swig
#             cmake --build build --config Release --parallel 2
#             objcopy --only-keep-debug build/libtorrent4j.so build/libtorrent4j.so.debug
#             curl --upload-file build/libtorrent4j.so https://transfer.sh/libtorrent4j.so
#             readelf -d build/libtorrent4j.so
#       - uses: actions/upload-artifact@v2
#         with:
#           name: libtorrent4j-linux-cmake
#           path: |
#             build/libtorrent4j.so
#             build/libtorrent4j.so.debug
#           retention-days: 5

  x86_64-b2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
#          bind_mount_repository: true
          image_additional_mb: 10000
          commands: |
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt install software-properties-common
            sudo apt update
            sudo add-apt-repository ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt install gcc-10
            wget -nv -O boost.tar.gz https://boostorg.jfrog.io/artifactory/main/release/${BOOST_DOT_VERSION}/source/boost_${BOOST_VERSION}.tar.gz
            tar xzf boost.tar.gz
            mv boost_${BOOST_VERSION} boost
            cd boost
            ./bootstrap.sh
            cd ..
            wget -nv -O openssl.tar.gz https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
            tar xzf openssl.tar.gz
            cd openssl-${OPENSSL_VERSION}
            ./Configure linux-armv7 ${OPENSSL_NO_OPTS} -fPIC --prefix=${PWD}/../openssl
            make &> /dev/null
            make install_sw &> /dev/null
            cd ..
            export BOOST_ROOT=${PWD}/boost
            export OPENSSL_ROOT=${PWD}/openssl
            export LIBTORRENT_ROOT=${PWD}/swig/deps/libtorrent
            cd swig
            ${BOOST_ROOT}/b2 -j2 --user-config=config/linux-x86-config.jam variant=release toolset=gcc-armv7 target-os=linux location=bin/release/linux/armv7
            cd ..
            objcopy --only-keep-debug swig/bin/release/linux/armv7/libtorrent4j.so swig/bin/release/linux/armv7/libtorrent4j.so.debug
            strip --strip-unneeded -x swig/bin/release/linux/armv7/libtorrent4j.so
            curl --upload-file build/libtorrent4j.so https://transfer.sh/libtorrent4j.so
            readelf -d swig/bin/release/linux/armv7/libtorrent4j.so
            cp swig/bin/release/linux/x86_64/libtorrent4j.so .
            ./gradlew test
