name: Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  BOOST_DOT_VERSION: "1.78.0"
  BOOST_VERSION: "1_78_0"
  OPENSSL_VERSION: "1.1.1m"
  OPENSSL_NO_OPTS: "no-deprecated no-shared no-makedepend no-static-engine no-stdio no-posix-io no-threads no-ui-console no-zlib no-zlib-dynamic -fno-strict-aliasing -fvisibility=hidden -O3"
  CXX: g++-10
  CC: gcc-10

jobs:
  armv7-b2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: pguyot/arm-runner-action@v2
        with:
          cpu: cortex-a7
          base_image: raspios_lite:latest
          cpu_info: cpuinfo/raspberrypi_3b
          image_additional_mb: 5000
          commands: |
            sudo apt-get -y update
            sudo apt-get -y install gcc-10
            sudo apt-get -y install cmake
            sudo apt-get -y install libssl-dev
            wget -nv -O openssl.tar.gz https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
            tar xzf openssl.tar.gz
            cd openssl-${OPENSSL_VERSION}
            ./Configure linux-generic32 ${OPENSSL_NO_OPTS} -fPIC --prefix=${PWD}/../openssl
            make &> /dev/null
            make install_sw &> /dev/null
            cd ..
            wget -nv -O boost.tar.gz https://boostorg.jfrog.io/artifactory/main/release/${BOOST_DOT_VERSION}/source/boost_${BOOST_VERSION}.tar.gz
            tar xzf boost.tar.gz
            mv boost_${BOOST_VERSION} boost
            cd boost
            ./bootstrap.sh
            cd ..
            export BOOST_ROOT=${PWD}/boost
            export OPENSSL_ROOT=${PWD}/openssl
            export LIBTORRENT_ROOT=${PWD}/swig/deps/libtorrent
            cd swig
            ${BOOST_ROOT}/b2 -j2 --user-config=config/linux-armv7-config.jam variant=release toolset=gcc-armv7 target-os=linux location=bin/release/linux/armv7
            cd ..
            objcopy --only-keep-debug swig/bin/release/linux/armv7/libtorrent4j.so swig/bin/release/linux/armv7/libtorrent4j.so.debug
            strip --strip-unneeded -x swig/bin/release/linux/armv7/libtorrent4j.so
            curl --upload-file swig/bin/release/linux/armv7/libtorrent4j.so https://transfer.sh/libtorrent4j.so
            readelf -d swig/bin/release/linux/armv7/libtorrent4j.so
      - uses: actions/upload-artifact@v2
        with:
          name: libtorrent4j-armv7-b2
          path: |
            swig/bin/release/linux/armv7/libtorrent4j.so
            retention-days: 30
